//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LayoutRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayoutRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Firlansa.WebUI.AppCode.Resources.UserUI.LayoutRes.LayoutRes", typeof(LayoutRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ünvan.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əlaqə məlumatları.
        /// </summary>
        public static string Contact_Info {
            get {
                return ResourceManager.GetString("Contact Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endirimlər.
        /// </summary>
        public static string Discounts {
            get {
                return ResourceManager.GetString("Discounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektron poçtunuzu daxil edin.
        /// </summary>
        public static string Enter_your_email {
            get {
                return ResourceManager.GetString("Enter your email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firlansa - onlayn geyim mağazası.
        /// </summary>
        public static string Firlansa___online_clothing_store {
            get {
                return ResourceManager.GetString("Firlansa - online clothing store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firlansa Onlayn geyim mağazası © 2019. Bütün huquqlar qorunur!.
        /// </summary>
        public static string Firlansa_Online_Clothing_Store__copy__2019__All_rights_reserved_ {
            get {
                return ResourceManager.GetString("Firlansa Online Clothing Store &copy; 2019. All rights reserved!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.E - B / 10:00 AM - 8:00 PM.
        /// </summary>
        public static string M___S___10_00_AM___8_00_PM {
            get {
                return ResourceManager.GetString("M - S / 10:00 AM - 8:00 PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abunə olun.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firlansa - onlayn geyim mağazasına xoş gəlmişsiniz.
        /// </summary>
        public static string Welcome_to_Firlansa___online_clothing_store {
            get {
                return ResourceManager.GetString("Welcome to Firlansa - online clothing store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Saatı.
        /// </summary>
        public static string Working_hours {
            get {
                return ResourceManager.GetString("Working hours", resourceCulture);
            }
        }
    }
}
