//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Firlansa.WebUI.AppCode.Resources.UserUI.AccountPage.AccountPage", typeof(AccountPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesab məlumatları.
        /// </summary>
        public static string Account_details {
            get {
                return ResourceManager.GetString("Account details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məhsulların məbləği.
        /// </summary>
        public static string Amount_of_products {
            get {
                return ResourceManager.GetString("Amount of products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to və hesab məlumatları..
        /// </summary>
        public static string and_account_details_ {
            get {
                return ResourceManager.GetString("and account details.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rəng.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarix.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çatdırılma Məbləği.
        /// </summary>
        public static string Delivery_amount {
            get {
                return ResourceManager.GetString("Delivery amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detallı.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektron Poçt.
        /// </summary>
        public static string Email_Address {
            get {
                return ResourceManager.GetString("Email Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabınızın idarə panelindən öz hesabınıza baxa bilərsiniz.
        /// </summary>
        public static string From_your_account_dashboard_you_can_view_your {
            get {
                return ResourceManager.GetString("From your account dashboard you can view your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mağazaya gedin.
        /// </summary>
        public static string Go_To_Shop {
            get {
                return ResourceManager.GetString("Go To Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salam.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Səhifə.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıxış edin.
        /// </summary>
        public static string Log_Out {
            get {
                return ResourceManager.GetString("Log Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mənim Hesabım.
        /// </summary>
        public static string My_Account {
            get {
                return ResourceManager.GetString("My Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirişlər.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to əd.
        /// </summary>
        public static string Num {
            get {
                return ResourceManager.GetString("Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ədəd.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to və ya.
        /// </summary>
        public static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifariş.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifarişlər.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödənilib.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrə.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qiymət.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məhsul.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to son sifarişlər.
        /// </summary>
        public static string recent_orders {
            get {
                return ResourceManager.GetString("recent orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qeydiyyatdan Keç.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrənin Təkrarını daxil edin.
        /// </summary>
        public static string Repeat_Password {
            get {
                return ResourceManager.GetString("Repeat Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ölçü.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifarişin çatdırılma ilə ümumi məbləği.
        /// </summary>
        public static string The_total_amount_of_the_order_with_delivery {
            get {
                return ResourceManager.GetString("The total amount of the order with delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hal-hazırda heç bir bildiriş yoxdur..
        /// </summary>
        public static string There_are_currently_no_notifications_ {
            get {
                return ResourceManager.GetString("There are currently no notifications.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yekun.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
    }
}
