//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContactForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Firlansa.WebUI.AppCode.Resources.UserUI.ContactForm.ContactForm", typeof(ContactForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakı.
        /// </summary>
        public static string Baku {
            get {
                return ResourceManager.GetString("Baku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filial.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boş ola bilməz.
        /// </summary>
        public static string CantBeEmpty {
            get {
                return ResourceManager.GetString("CantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şərh.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizimlə Əlaqə.
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektron Poçt.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-poçt ünvanı səhvdir.
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28 may Nəsimi rayon Polis idarəsi ilə üzbəüz.
        /// </summary>
        public static string May_28__opposite_the_Nasimi_district_police_department_ {
            get {
                return ResourceManager.GetString("May 28, opposite the Nasimi district police department.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mağazamız.
        /// </summary>
        public static string Our_Store {
            get {
                return ResourceManager.GetString("Our Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon Nömrə.
        /// </summary>
        public static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şərh Yaz.
        /// </summary>
        public static string Post_Comment {
            get {
                return ResourceManager.GetString("Post Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dəstək.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-poçt ünvanınız paylaşılmayacaq. Tələb olunan sahələr qeyd olunub *.
        /// </summary>
        public static string Your_email_address_will_not_be_published__Required_fields_are_marked__ {
            get {
                return ResourceManager.GetString("Your email address will not be published. Required fields are marked *", resourceCulture);
            }
        }
    }
}
