//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AboutPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Firlansa.WebUI.AppCode.Resources.UserUI.AboutPage.AboutPage", typeof(AboutPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haqqımızda.
        /// </summary>
        public static string About_Us {
            get {
                return ResourceManager.GetString("About Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artıq minlərlə insan Firlansa&apos;dan çox razıdır.
        /// </summary>
        public static string Already_thousands_of_people_are_very_satisfied_by_Firlansa {
            get {
                return ResourceManager.GetString("Already thousands of people are very satisfied by Firlansa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pambıq qarışığı.
        /// </summary>
        public static string Cotton_blend {
            get {
                return ResourceManager.GetString("Cotton blend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoşbəxt müştərilər.
        /// </summary>
        public static string Happy_Customer {
            get {
                return ResourceManager.GetString("Happy Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onlayn Geyim Mağazası.
        /// </summary>
        public static string Online_Clothing_Store {
            get {
                return ResourceManager.GetString("Online Clothing Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mağazamız.
        /// </summary>
        public static string Our_Store {
            get {
                return ResourceManager.GetString("Our Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dəbli və keyfiyyətli məhsullar təqdim edirik.
        /// </summary>
        public static string Provide_fashionable_and_qualified_products {
            get {
                return ResourceManager.GetString("Provide fashionable and qualified products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyfiyyətli geyimlər.
        /// </summary>
        public static string Quality_Clothes {
            get {
                return ResourceManager.GetString("Quality Clothes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tam uyğun.
        /// </summary>
        public static string Straight_fit {
            get {
                return ResourceManager.GetString("Straight fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyfiyyətli geyimlərin ünvanı.
        /// </summary>
        public static string The_address_of_quality_clothes {
            get {
                return ResourceManager.GetString("The address of quality clothes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mağazamızı ziyarət edin.
        /// </summary>
        public static string Visit_Our_Store {
            get {
                return ResourceManager.GetString("Visit Our Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni məhsullar dizayn edirik. Siz onları inanılmaz qiymətlərlə alırsınız..
        /// </summary>
        public static string We_design_new_products__You_crowd_fund_them_at_incredible_prices_ {
            get {
                return ResourceManager.GetString("We design new products. You crowd-fund them at incredible prices.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axtardığınız hər şeyi bir yerdə topladıq.
        /// </summary>
        public static string We_have_collected_everything_you_are_looking_for_in_one_place {
            get {
                return ResourceManager.GetString("We have collected everything you are looking for in one place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firlansa&apos;ya Xoş gəlmişsiniz.
        /// </summary>
        public static string Welcome_Firlansa {
            get {
                return ResourceManager.GetString("Welcome Firlansa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biz nə edirik.
        /// </summary>
        public static string What_We_Do {
            get {
                return ResourceManager.GetString("What We Do", resourceCulture);
            }
        }
    }
}
