//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShopPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShopPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Firlansa.WebUI.AppCode.Resources.UserUI.ShopPage.ShopPage", typeof(ShopPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Səbətə əlavə et.
        /// </summary>
        public static string Add_to_Basket {
            get {
                return ResourceManager.GetString("Add to Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gələndə xəbər et.
        /// </summary>
        public static string Add_to_Notification {
            get {
                return ResourceManager.GetString("Add to Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilmişlərə əlavə et.
        /// </summary>
        public static string Add_to_Wishlist {
            get {
                return ResourceManager.GetString("Add to Wishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əlavə məlumat.
        /// </summary>
        public static string Additional_Information {
            get {
                return ResourceManager.GetString("Additional Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Səbət.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kateqoriyalar.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kateqoriya.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçim edin.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağla.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rəng.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifarişi Tamamla.
        /// </summary>
        public static string Complete_the_order {
            get {
                return ResourceManager.GetString("Complete the order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alış-Verİşə davam et.
        /// </summary>
        public static string Continue_shopping {
            get {
                return ResourceManager.GetString("Continue shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çatdırılma ünvanı.
        /// </summary>
        public static string Delivery_address {
            get {
                return ResourceManager.GetString("Delivery address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndi araşdır.
        /// </summary>
        public static string Discover_now {
            get {
                return ResourceManager.GetString("Discover now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Səbətə bax.
        /// </summary>
        public static string Go_to_Basket {
            get {
                return ResourceManager.GetString("Go to Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıralama.
        /// </summary>
        public static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ölkə daxili çatdırılma mümkündür.
        /// </summary>
        public static string Local_delivery_available_ {
            get {
                return ResourceManager.GetString("Local delivery available.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zəhmət olmasa məlumatları düzgün daxil edin, əks halda çatdırılma baş vermyəcək.
        /// </summary>
        public static string Please_enter_the_information_correctly__otherwise_the_delivery_will_not_take_place {
            get {
                return ResourceManager.GetString("Please enter the information correctly, otherwise the delivery will not take plac" +
                        "e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poçt kodu (İndeksi).
        /// </summary>
        public static string Postal_Code__Index_ {
            get {
                return ResourceManager.GetString("Postal Code (Index)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məhsullar.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ətraflı Baxış.
        /// </summary>
        public static string Quickview {
            get {
                return ResourceManager.GetString("Quickview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnzibati ərazini seçin.
        /// </summary>
        public static string Select_the_administrative_area {
            get {
                return ResourceManager.GetString("Select the administrative area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mağaza.
        /// </summary>
        public static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alış-Veriş Səbəti.
        /// </summary>
        public static string Shopping_Cart {
            get {
                return ResourceManager.GetString("Shopping Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxşar məhsullar.
        /// </summary>
        public static string Similar_Products {
            get {
                return ResourceManager.GetString("Similar Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ölçü.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məhsul yoxdur.
        /// </summary>
        public static string There_is_no_product {
            get {
                return ResourceManager.GetString("There is no product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxşar məhsul yoxdur.
        /// </summary>
        public static string There_is_no_Similar_Product {
            get {
                return ResourceManager.GetString("There is no Similar Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilmişlər siyahısı boşdur.
        /// </summary>
        public static string Wishlist_is_empty {
            get {
                return ResourceManager.GetString("Wishlist is empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sebetiniz Bosdur.
        /// </summary>
        public static string Your_cart_is_empty {
            get {
                return ResourceManager.GetString("Your cart is empty", resourceCulture);
            }
        }
    }
}
